apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  labels:
    app: sample-node.js app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000  # Replace with the port your app runs on
  selector:
    app: sample-node.js app
